language: ruby
rvm:
  - 2.0.0
env:
  - DB=sqlite
  - DB=postgresql
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake test
before_script:
  - psql -c 'create database treebook_test' -U postgres
bundler_args: --binstubs=./bundler_stubs
addons:
  code_climate:
    repo_token:
      secure: "YexDVhPLUoNHKg4G6N2Bsv78SmVpPgfT7xQfBc4imbzsNXyfl5QS+iEGmNW12VeS68IVZrMR9y1hlF9ydYVCSGVDzkXJOeoE8/Ioi8CRW0PtAoh4qSkjjwadC0e2aiBUpE0ZKwLs6OqQU3cu5asVt2OA2OgtPooVcaGaJFiGODI="
